version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - my_pgdata:/var/lib/postgresql/data
    ports:
      - 5431:5432

volumes:
  my_pgdata:
